Breaking out of nesting loops in Python can be hard. It can be easy with generators.

First, we do it the ordinary way.

In [1]:
N_COLUMNS = 5
N_LINES = 3

import numpy as np

a = np.arange(N_LINES * N_COLUMNS).reshape(N_LINES, N_COLUMNS)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
please_break = False
for line in range(N_LINES):
    for column in range(N_COLUMNS):
        if a[line, column] == 8:
            please_break = True
            break
        a[line, column] = -1
    if please_break:
        break
        
print(a)    

[[-1 -1 -1 -1 -1]
 [-1 -1 -1  8  9]
 [10 11 12 13 14]]


Now we do it the easy way with generators.

In [3]:
a = np.arange(N_LINES * N_COLUMNS).reshape(N_LINES, N_COLUMNS)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
def get_array_indexes(n_rows, n_columns):
    for row in range(n_rows):
        for column in range(n_columns):
            yield row, column

In [5]:
for line, column in get_array_indexes(N_LINES, N_COLUMNS):
    if a[line, column] == 6:
        break
    a[line, column] = -1

In [6]:
print(a)

[[-1 -1 -1 -1 -1]
 [-1  6  7  8  9]
 [10 11 12 13 14]]


I learned this technique from one of Raymond Hettinger's presentations.
Thanks Raymond!